# Generated by Django 4.0.5 on 2022-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=4667742718701, help_text='13 Character <a href="https://www.isbn-international.org                            /content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN'),
        ),
    ]
